baseURL = "http://riron.github.io/"
languageCode = "fr"
title = "Orion Charlier"
theme = "paper"

defaultContentLanguage = "fr"

hasCJKLanguage = true
paginate = 3

[permalinks]
posts = "/posts/:title/"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[params]
color = 'wheat'

twitter = 'OrionCharlier'
github = 'Riron'
rss = true

# home page profile
avatar = 'GRAVATAR_EMAIL'
name = 'Orion Charlier'
bio = 'Développeur Full Stack Freelance'

disableHLJS = true
